version: "3"

services:

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "50051:50051"

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "7860:7860"
    depends_on:
      - backend
