# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/audio.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'protos/audio.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12protos/audio.proto\x12\nstoryaudio\"\"\n\x0c\x41udioRequest\x12\x12\n\nstory_text\x18\x01 \x01(\t\"#\n\rAudioResponse\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x32Y\n\x11StoryAudioService\x12\x44\n\rGenerateAudio\x12\x18.storyaudio.AudioRequest\x1a\x19.storyaudio.AudioResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.audio_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUDIOREQUEST']._serialized_start=34
  _globals['_AUDIOREQUEST']._serialized_end=68
  _globals['_AUDIORESPONSE']._serialized_start=70
  _globals['_AUDIORESPONSE']._serialized_end=105
  _globals['_STORYAUDIOSERVICE']._serialized_start=107
  _globals['_STORYAUDIOSERVICE']._serialized_end=196
# @@protoc_insertion_point(module_scope)
